[advisories]
unmaintained = "all"
yanked = "deny"

[bans]
multiple-versions = "allow"
wildcards = 'deny'
deny = [
    { crate = "openssl", use-instead = "rustls" },
    { crate = "openssl-sys", use-instead = "rustls" },
    "libssh2-sys",
]

[licenses]
allow = [
    "MIT",
]
unused-allowed-license = "deny"

[sources]
unknown-git = "deny"
unknown-registry = "deny"
